### ISSUE TITLE
Need a help for solving the errors

### ISSUE THREAD

**Issue by yw1055** [CoppeliaRobotics/simOMPL#11]
Hi whom may concern,
   I am following the instructions to plug in OMPL for CoppeliaSim:
    $ git clone https://github.com/CoppeliaRobotics/simExtOMPL.git
$ cd simOMPL
$ git checkout coppeliasim-v4.5.1-rev4
$ mkdir -p build && cd build
$ cmake -DCMAKE_BUILD_TYPE=Release ..
$ cmake --build .
$ cmake --install .
However, when I run  cmake -DCMAKE_BUILD_TYPE=Release .., it shows the errors as follow:
yiwang@yiwang:~/Downloads/CoppeliaSim_Edu_V4_5_1_rev4_Ubuntu20_04/simOMPL$ cmake -DCMAKE_BUILD_TYPE=Release
CMake Warning:
  No source or binary directory provided.  Both will be assumed to be the
  same as the current working directory, but note that this warning will
  become a fatal error in future CMake releases.

-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found version "1.71.0") found components: system serialization 
CMake Error at CMakeLists.txt:19 (find_package):
  By not providing "FindCoppeliaSim.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "CoppeliaSim", but CMake did not find one.

  Could not find a package configuration file provided by "CoppeliaSim"
  (requested version 4.5.1.7) with any of the following names:

    CoppeliaSimConfig.cmake
    coppeliasim-config.cmake

  Add the installation prefix of "CoppeliaSim" to CMAKE_PREFIX_PATH or set
  "CoppeliaSim_DIR" to a directory containing one of the above files.  If
  "CoppeliaSim" provides a separate development package or SDK, be sure it
  has been installed.

-- Configuring incomplete, errors occurred!
See also "/home/yiwang/Downloads/CoppeliaSim_Edu_V4_5_1_rev4_Ubuntu20_04/simOMPL/CMakeFiles/CMakeOutput.log".

Could anyone give me a suggestion to fix it? If so, I would appreciate it. This issue has bothered me for a while.
Thanks again.

**Comment by fferri** [comment]
> However, when I run
> `cmake -DCMAKE_BUILD_TYPE=Release ..`
> it shows the errors as follow:
> yiwang@yiwang:~/Downloads/CoppeliaSim_Edu_V4_5_1_rev4_Ubuntu20_04/simOMPL$ `cmake -DCMAKE_BUILD_TYPE=Release`
> CMake Warning: No source or binary directory provided

that's not the same command.
