### ISSUE TITLE
error on installing simompl

### ISSUE THREAD

**Issue by yw1055** [CoppeliaRobotics/simOMPL#12]
To whom it may concern,

I am trying to install simOMPL using the provided instructions. However, I encountered the following errors:

  ~/Downloads/CoppeliaSim_Edu_V4_5_1_rev4_Ubuntu20_04/simOMPL/build$ cmake -DCMAKE_BUILD_TYPE=Release ..
CMake Error at CMakeLists.txt:19 (find_package):
  By not providing "FindCoppeliaSim.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "CoppeliaSim", but CMake did not find one.

  Could not find a package configuration file provided by "CoppeliaSim"
  (requested version 4.5.1.7) with any of the following names:

    CoppeliaSimConfig.cmake
    coppeliasim-config.cmake

  Add the installation prefix of "CoppeliaSim" to CMAKE_PREFIX_PATH or set
  "CoppeliaSim_DIR" to a directory containing one of the above files.  If
  "CoppeliaSim" provides a separate development package or SDK, be sure it
  has been installed.

-- Configuring incomplete, errors occurred!
See also "Downloads/CoppeliaSim_Edu_V4_5_1_rev4_Ubuntu20_04/simOMPL/CMakeFiles/CMakeOutput.log".

Does anyone know how to fix this? BTW, I tried to change line19 to " 4.5.1-rev4", but I cannot work.
I appreciate it.

**Comment by fferri** [comment]
Plugins are normally put into the 'programming' directory of coppeliaSim.

**Comment by yw1055** [comment]
Thanks for the rapid response and I will try it later!
Bests,
Yi
________________________________
